export {default as ContactUS} from './ContactUS/ContactUs'
export {default as Blog} from './blog/Blog'
export {default as Features} from './features/Features'
export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as LandingPage} from './landingPage/LandingPage'
export {default as OurClinets} from './OurClients/OurClinets'
export {default as Products} from './products/Products'
export {default as Reviews} from './reviews/Reviews'
export {default as AboutUS } from './AboutUS/AboutUs'